### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by silverfox0000** [xymb-endcrystalme/LinearPaper#5]
Seems the server unable to find structures like stronghold then ender eye not working too
![java_mR0CqLAp9B](https://user-images.githubusercontent.com/52673655/229370667-a17644dd-b9db-4611-8b41-e8ae60a77ba1.png)

**Comment by xymb-endcrystalme** [comment]
Yeah, I'll probably be retiring this project.
I want to focus on Folia.

**Comment by silverfox0000** [comment]
The problem has been solved, most likely it is a problem with the paper itself (and upgraded world from old type), because on the local server the structures are fine located and the ender eye works too
