### ISSUE TITLE
ZstdIOException: Restored data doesn't match checksum

### ISSUE THREAD

**Issue by tienthanh2929** [xymb-endcrystalme/LinearPaper#8]
Hosted for two weeks straight, no problem.
The server has roughly over 60 players daily and a total of 30GB of world size.
Then this error appeared, causing the server to crash.

I stand in the region that caused the crash; no problem. But after a few players joined in, it crashed again in the same chunk.

No invalid items or anything from the players; no sight of a lag machine.

After deleting the corrupted region file and converting back to MCA, the problem is gone.

https://pastes.dev/Si1xas5As4

**Comment by xymb-endcrystalme** [comment]
Wrong project. You're using Kaiiju, not LinearPaper.

What OS are you using? `Restored data doesn't match checksum` problem should really happen only if moves on your OS aren't atomic & your chunk write crashes during the operation.
